window.QUACKI_LEADERBOARD = {
  SUPABASE_URL: "https://dxangiptqfsqlptnltdr.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4YW5naXB0cWZzcWxwdG5sdGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyMTA0MDMsImV4cCI6MjA5Nzc4NjQwM30.6tLWyV5cWUoceC9LJ6EkgT4O1B7AlpHahKg3BCGJEAA",
  TABLE: "scores"
};
